### PR TITLE
Introduce BACKUP_DISABLED variable to disable backup if it's set to true

### PR DESCRIPTION
**Pull request by kaifungchong**
@faizhasim Please review.

### CODE REVIEW

**Comment by faizhasim** [comment]
Take that logic, and implement it in scripts/configure-cron instead.

**Comment by ykt** [comment]
Ok she is updating on script/configure-cron. At first I thought you wanna add it in cronjob itself:

```
root test ! -x $BACKUP_DISABLED || /usr/local/bin/innobackupex-runner  >> /tmp/cronlog 2>&1
```

**Comment by ykt** [comment]
Ok, for me.

**Comment by faizhasim** [comment]
@ykt or that. either changing the cronjob behaviour or make sure that cronjob doesn't run at all, will achieve the same effect.

**Pull request merged**
